USE [master]
GO

/****** Object:  Database [AdvokatskaKancelarija]    Script Date: 11/24/2021 2:40:22 AM ******/
CREATE DATABASE [AdvokatskaKancelarija]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdvokatskaKancelarija', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AdvokatskaKancelarija.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdvokatskaKancelarija_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AdvokatskaKancelarija_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvokatskaKancelarija].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET  MULTI_USER 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdvokatskaKancelarija] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdvokatskaKancelarija] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AdvokatskaKancelarija] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AdvokatskaKancelarija] SET  READ_WRITE 
GO


